### ISSUE TITLE
sample-simple.cfg does not work

### ISSUE THREAD

**Issue by cbluth** [glauth/glauth#71] opened 2019-01-07 14:06 UTC
sample-simple.cfg does not work
I am getting this in the log:
```

14:03:07.276592 main ▶ CRIT 001 Configuration file error: Near line 64 (last key parsed 'users.passappsha256'): Key 'users.passappsha256' has already been defined.

```

**Comment by online-stuff** [comment] 2019-03-25 07:36
So remove line 64....
passappsha256 = ["6478579e37aff45f013e14eeb30b3cc56c72ccdc310123bcdf53e0333e3f416a"]


This is just before it
[code]
# This user record shows all of the possible fields available
[[users]]
  name = "johndoe"

[/code]

**Comment by z41** [comment] 2019-12-10 20:13
Same issue. The problem is that this config is used by Dockerfile, so it doesn't work when running with defaults. Worth fixing imho.

**Comment by anoma** [comment] 2019-12-14 08:26
This is not the only place where the sample config does not work by default.  Also the online and the generated by default sample configs do not match.

None of these are show stoppers but it is a needless barrier to entry.

**Comment by DeepDiver1975** [comment] 2020-02-21 08:20
fixed by https://github.com/glauth/glauth/pull/79 - can be closed @butonic

**Comment by butonic** [comment] 2020-02-21 16:08
fixed in dev

**Closed by butonic** 2020-02-21 16:08 UTC
